TRUNCATE TABLE event CASCADE;
TRUNCATE TABLE content CASCADE;
TRUNCATE TABLE file CASCADE;
TRUNCATE TABLE generationGeometry CASCADE;
TRUNCATE TABLE generation CASCADE;    
TRUNCATE TABLE producer CASCADE;
