#ifndef __DATA_SERVER_TYPEDEFS_IDL
#define __DATA_SERVER_TYPEDEFS_IDL


module SmartMet
{

module DataServer
{

module Corba
{


typedef unsigned long long CorbaParamId;
typedef float CorbaParamValue;

typedef sequence<unsigned long> CorbaULongList;
typedef sequence<CorbaParamValue> CorbaParamValueList;
typedef sequence<double> CorbaDoubleList;



struct CorbaAttribute
{
  string name;
  string value;
};

typedef sequence<CorbaAttribute> CorbaAttributeList;



struct CorbaValueRecord
{
  unsigned long    fileId;
  unsigned long    messageIndex;
  octet            coordinateType;
  short            areaInterpolationMethod;
  double           x;
  double           y;
  CorbaParamValue  value;
  long             result;
};

typedef sequence<CorbaValueRecord> CorbaValueRecordList;



struct CorbaCoordinate
{
  double x;
  double y;
};

typedef sequence<CorbaCoordinate> CorbaCoordinateList;
typedef sequence<CorbaCoordinateList> CorbaPolygonPath;



struct CorbaGridValue
{
  double x;
  double y;
  float  value;
};

typedef sequence<CorbaGridValue> CorbaGridValueList;




struct CorbaGridData
{
  unsigned long       serverId;
  unsigned long       producerId;
  unsigned long       generationId;
  unsigned long       fileId;
  octet               fileType;
  string              fileName;
  unsigned long       messageIndex;
  string              forecastTime;
  short               forecastType;
  short               forecastNumber;
  string              gribParameterId;
  unsigned long       grib1ParameterLevelId;
  unsigned long       grib2ParameterLevelId;
  string              gribParameterName;
  string              fmiParameterId;
  unsigned long       fmiParameterLevelId;
  string              fmiParameterName;
  string              newbaseParameterId;
  string              newbaseParameterName;
  long                parameterLevel;
  unsigned long	      geometryId;
  unsigned long       projection;
  unsigned long       columns;
  unsigned long       rows;  
  CorbaAttributeList  projectionAttributes;
  CorbaParamValueList valueList;
};




struct CorbaGridCoordinates
{
  unsigned long       projection;  
  unsigned long       columns;
  unsigned long       rows;  
  CorbaAttributeList  projectionAttributes;
  octet               coordinateType;  
  CorbaCoordinateList coordinateList;
};



typedef sequence<octet> CorbaByteData;
typedef sequence<CorbaByteData> CorbaByteDataSequence;




};
};
};


#endif
