#ifndef __DATA_SERVER_SERVICE_INTERFACE_IDL
#define __DATA_SERVER_SERVICE_INTERFACE_IDL

#include "DataServer_typedefs.idl"



module SmartMet
{

module DataServer
{

module Corba
{


interface ServiceInterface
{
  C::Result  getGridAttributeList(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,out C::AttributeRecList attributeList);
  
  
  C::Result  getGridProperties(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,out C::PropertySettingList propertyList);
  C::Result  getGridCoordinates(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,out C::GridCoordinates coordinates);
  C::Result  getGridLatlonCoordinatesByGeometry(in C::SessionId sessionId,inout C::AttributeRecList attributeList,out C::GridCoordinates coordinates);
  C::Result  getGridData(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,out C::GridData data);
  C::Result  getGridFileCount(in C::SessionId sessionId,out C::UInt32 count);
  C::Result  getGridMessageBytes(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,out C::ByteData messageBytes,out C::UInt32List messageSections);
  
  C::Result  getPropertyValuesByCoordinates(in C::SessionId sessionId,in string propertyName,in C::CoordinateList latlonCoordinates,out C::ParameterValueList values);

  C::Result  getGridValueByPoint(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::Float64 x,in C::Float64 y,in C::Int16 areaInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValue value);
  C::Result  getGridValueByLevelAndPoint(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::Int32 level1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Int32 level2,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::Float64 x,in C::Float64 y,in C::Int16 areaInterpolationMethod,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValue value);
  C::Result  getGridValueByTimeAndPoint(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::CoordinateType coordinateType,in C::Float64 x,in C::Float64 y,in C::Int16 areaInterpolationMethod,in C::Int16 timeInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValue value);
  C::Result  getGridValueByTimeLevelAndPoint(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::Int32 level1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Int32 level2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::Int32 level3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Int32 level4,in C::Timestamp newTime,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::Float64 x,in C::Float64 y,in C::Int16 areaInterpolationMethod,in C::Int16 timeInterpolationMethod,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValue value);

  C::Result  getGridValueListByCircle(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::Float64 origoX,in C::Float64 origoY,in C::Float64 radius,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByPointList(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::CoordinateList pointList,in C::Int16 areaInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByPolygon(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::CoordinateList polygonPoints,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByPolygonPath(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::PolygonPath polygonPath,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByLevelAndCircle(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::Float64 origoX,in C::Float64 origoY,in C::Float64 radius,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByLevelAndPointList(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::CoordinateList pointList,in C::Int16 areaInterpolationMethod,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByLevelAndPolygon(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::CoordinateList polygonPoints,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByLevelAndPolygonPath(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::PolygonPath polygonPath,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByRectangle(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::Float64 x1,in C::Float64 y1,in C::Float64 x2,in C::Float64 y2,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByTimeAndCircle(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::CoordinateType coordinateType,in C::Float64 origoX,in C::Float64 origoY,in C::Float64 radius,in C::Int16 timeInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByTimeAndPointList(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::CoordinateType coordinateType,in C::CoordinateList pointList,in C::Int16 areaInterpolationMethod,in C::Int16 timeInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByTimeAndPolygon(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::CoordinateType coordinateType,in C::CoordinateList polygonPoints,in C::Int16 timeInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByTimeAndPolygonPath(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::CoordinateType coordinateType,in C::PolygonPath polygonPath,in C::Int16 timeInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByTimeLevelAndCircle(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::Float64 origoX,in C::Float64 origoY,in C::Float64 radius,in C::Int16 timeInterpolationMethod,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByTimeLevelAndPointList(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::CoordinateList pointList,in C::Int16 areaInterpolationMethod,in C::Int16 timeInterpolationMethod,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByTimeLevelAndPolygon(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::CoordinateList polygonPoints,in C::Int16 timeInterpolationMethod,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);
  C::Result  getGridValueListByTimeLevelAndPolygonPath(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::PolygonPath polygonPath,in C::Int16 timeInterpolationMethod,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::GridValueList valueList);

  C::Result  getGridValueVector(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByCoordinateList(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::CoordinateList coordinates,in C::Int16 areaInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByGeometry(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByRectangle(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::UInt32 columns,in C::UInt32 rows,in C::Float64 x,in C::Float64 y,in C::Float64 xStep,in C::Float64 yStep,in C::Int16 areaInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByLevel(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByLevelAndCoordinateList(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::CoordinateList coordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByLevelAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByTime(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::Int16 timeInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByTimeAndCoordinateList(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::CoordinateType coordinateType,in C::CoordinateList coordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByTimeAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByTimeAndLevel(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::Int16 areaInterpolationMethod,in C::Int16 timeInterpolationMethod,in C::Int16 levelInterpolationMethod,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByTimeLevelAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);
  C::Result  getGridValueVectorByTimeLevelAndCoordinateList(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::CoordinateType coordinateType,in C::CoordinateList coordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ParameterValueList values);

  C::Result  getGridIsobands(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByGeometry(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByGrid(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByLevel(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByLevelAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByLevelAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByTime(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByTimeAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByTimeAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByTimeAndLevel(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByTimeLevelAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsobandsByTimeLevelAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::ParameterValueList contourLowValues,in C::ParameterValueList contourHighValues,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);

  C::Result  getGridIsolines(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::ParameterValueList contourValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByGeometry(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::ParameterValueList contourValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByGrid(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::ParameterValueList contourValues,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByLevel(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::ParameterValueList contourValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByLevelAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::ParameterValueList contourValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByLevelAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::ParameterValueList contourValues,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByTime(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::ParameterValueList contourValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByTimeAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::ParameterValueList contourValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByTimeAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::ParameterValueList contourValues,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByTimeAndLevel(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::ParameterValueList contourValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByTimeLevelAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::ParameterValueList contourValues,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);
  C::Result  getGridIsolinesByTimeLevelAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::ParameterValueList contourValues,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::ByteDataSequence contours);

  C::Result  getGridStreamlines(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByGeometry(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByGrid(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByLevel(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByLevelAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByLevelAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Float64 newLevel,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByTime(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByTimeAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByTimeAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::Timestamp newTime,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByTimeAndLevel(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByTimeLevelAndGeometry(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);
  C::Result  getGridStreamlinesByTimeLevelAndGrid(in C::SessionId sessionId,in C::FileId fileId1,in C::MessageIndex messageIndex1,in C::FileId fileId2,in C::MessageIndex messageIndex2,in C::FileId fileId3,in C::MessageIndex messageIndex3,in C::FileId fileId4,in C::MessageIndex messageIndex4,in C::Timestamp newTime,in C::Float64 newLevel,in C::UInt32 gridWidth,in C::UInt32 gridHeight,in C::CoordinateList gridLatLonCoordinates,inout C::AttributeRecList attributeList,in C::UInt32 modificationOperation,in C::Float64List modificationParameters,out C::ByteDataSequence streamlines);

  C::Result  getGridValueVectorByPoint(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,in C::CoordinateType coordinateType,in C::Float64 x,in C::Float64 y,in C::UInt32 vectorType,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,out C::Float64List valueVector);

  C::Result  getMultipleGridValues(in C::SessionId sessionId,in C::UInt32 modificationOperation, in C::Float64List modificationParameters,inout C::ValueRecordList valueRecordList);
};  


};
};
};

#endif
