#ifndef __DATA_SERVER_SERVICE_INTERFACE_IDL
#define __DATA_SERVER_SERVICE_INTERFACE_IDL

#include "DataServer_typedefs.idl"


module SmartMet
{

module DataServer
{

module Corba
{


interface ServiceInterface
{
  long  getGridAttributeList(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,out CorbaAttributeList attributeList);
  long  getGridCoordinates(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,out CorbaGridCoordinates coordinates);
  long  getGridData(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,out CorbaGridData data);
  long  getGridFileCount(in long long sessionId,out unsigned long count);
  long  getGridMessageBytes(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,out CorbaByteData messageBytes,out CorbaULongList messageSections);
  
  long  getPropertyValuesByCoordinates(in long long sessionId,in string propertyName,in CorbaCoordinateList latlonCoordinates,out CorbaParamValueList values);

  long  getGridValueByPoint(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in double x,in double y,in short areaInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValue value);
  long  getGridValueByLevelAndPoint(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in long level1,in unsigned long fileId2,in unsigned long messageIndex2,in long level2,in long newLevel,in octet coordinateType,in double x,in double y,in short areaInterpolationMethod,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValue value);
  long  getGridValueByTimeAndPoint(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in octet coordinateType,in double x,in double y,in short areaInterpolationMethod,in short timeInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValue value);
  long  getGridValueByTimeLevelAndPoint(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in long level1,in unsigned long fileId2,in unsigned long messageIndex2,in long level2,in unsigned long fileId3,in unsigned long messageIndex3,in long level3,in unsigned long fileId4,in unsigned long messageIndex4,in long level4,in unsigned long long newTime,in long newLevel,in octet coordinateType,in double x,in double y,in short areaInterpolationMethod,in short timeInterpolationMethod,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValue value);

  long  getGridValueListByCircle(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in double origoX,in double origoY,in double radius,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByPointList(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in CorbaCoordinateList pointList,in short areaInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByPolygon(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in CorbaCoordinateList polygonPoints,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByPolygonPath(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in CorbaPolygonPath polygonPath,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByLevelAndCircle(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in octet coordinateType,in double origoX,in double origoY,in double radius,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByLevelAndPointList(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in octet coordinateType,in CorbaCoordinateList pointList,in short areaInterpolationMethod,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByLevelAndPolygon(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in octet coordinateType,in CorbaCoordinateList polygonPoints,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByLevelAndPolygonPath(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in octet coordinateType,in CorbaPolygonPath polygonPath,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByRectangle(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in double x1,in double y1,in double x2,in double y2,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByTimeAndCircle(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in octet coordinateType,in double origoX,in double origoY,in double radius,in short timeInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByTimeAndPointList(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in octet coordinateType,in CorbaCoordinateList pointList,in short areaInterpolationMethod,in short timeInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByTimeAndPolygon(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in octet coordinateType,in CorbaCoordinateList polygonPoints,in short timeInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByTimeAndPolygonPath(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in octet coordinateType,in CorbaPolygonPath polygonPath,in short timeInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByTimeLevelAndCircle(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in octet coordinateType,in double origoX,in double origoY,in double radius,in short timeInterpolationMethod,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByTimeLevelAndPointList(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in octet coordinateType,in CorbaCoordinateList pointList,in short areaInterpolationMethod,in short timeInterpolationMethod,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByTimeLevelAndPolygon(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in octet coordinateType,in CorbaCoordinateList polygonPoints,in short timeInterpolationMethod,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);
  long  getGridValueListByTimeLevelAndPolygonPath(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in octet coordinateType,in CorbaPolygonPath polygonPath,in short timeInterpolationMethod,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaGridValueList valueList);

  long  getGridValueVector(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByCoordinateList(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in CorbaCoordinateList coordinates,in short areaInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByGeometry(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByRectangle(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in unsigned long columns,in unsigned long rows,in double x,in double y,in double xStep,in double yStep,in short areaInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByLevel(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByLevelAndCoordinateList(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in octet coordinateType,in CorbaCoordinateList coordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByLevelAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByTime(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in short timeInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByTimeAndCoordinateList(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in octet coordinateType,in CorbaCoordinateList coordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByTimeAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByTimeAndLevel(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in short areaInterpolationMethod,in short timeInterpolationMethod,in short levelInterpolationMethod,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByTimeLevelAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);
  long  getGridValueVectorByTimeLevelAndCoordinateList(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in octet coordinateType,in CorbaCoordinateList coordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaParamValueList values);

  long  getGridIsobands(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByGeometry(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByGrid(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByLevel(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByLevelAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByLevelAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByTime(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByTimeAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByTimeAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByTimeAndLevel(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByTimeLevelAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsobandsByTimeLevelAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in CorbaParamValueList contourLowValues,in CorbaParamValueList contourHighValues,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);

  long  getGridIsolines(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in CorbaParamValueList contourValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByGeometry(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in CorbaParamValueList contourValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByGrid(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in CorbaParamValueList contourValues,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByLevel(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in CorbaParamValueList contourValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByLevelAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in CorbaParamValueList contourValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByLevelAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in CorbaParamValueList contourValues,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByTime(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in CorbaParamValueList contourValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByTimeAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in CorbaParamValueList contourValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByTimeAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in CorbaParamValueList contourValues,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByTimeAndLevel(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in CorbaParamValueList contourValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByTimeLevelAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in CorbaParamValueList contourValues,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);
  long  getGridIsolinesByTimeLevelAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in CorbaParamValueList contourValues,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaByteDataSequence contours);

  long  getGridStreamlines(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByGeometry(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByGrid(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByLevel(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByLevelAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByLevelAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in long newLevel,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByTime(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByTimeAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByTimeAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long long newTime,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByTimeAndLevel(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByTimeLevelAndGeometry(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);
  long  getGridStreamlinesByTimeLevelAndGrid(in long long sessionId,in unsigned long fileId1,in unsigned long messageIndex1,in unsigned long fileId2,in unsigned long messageIndex2,in unsigned long fileId3,in unsigned long messageIndex3,in unsigned long fileId4,in unsigned long messageIndex4,in unsigned long long newTime,in long newLevel,in unsigned long gridWidth,in unsigned long gridHeight,in CorbaCoordinateList gridLatLonCoordinates,inout CorbaAttributeList attributeList,in unsigned long modificationOperation,in CorbaDoubleList modificationParameters,out CorbaByteDataSequence streamlines);

  long  getGridValueVectorByPoint(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in double x,in double y,in unsigned long vectorType,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,out CorbaDoubleList valueVector);

  long  getMultipleGridValues(in long long sessionId,in unsigned long modificationOperation, in CorbaDoubleList modificationParameters,inout CorbaValueRecordList valueRecordList);
};  


};
};
};

#endif
