#ifndef __DATA_SERVER_SERVICE_INTERFACE_IDL
#define __DATA_SERVER_SERVICE_INTERFACE_IDL

#include "DataServer_typedefs.idl"


module SmartMet
{

module DataServer
{

module Corba
{


interface ServiceInterface
{
  long  getGridAttributeList(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,out CorbaAttributeList attributeList);
  long  getGridCoordinates(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,out CorbaGridCoordinates coordinates);
  long  getGridData(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,out CorbaGridData data);
  long  getGridValue(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in double x,in double y,in octet interpolationMethod,out CorbaParamValue value);
  long  getGridValueList(in long long sessionId,inout CorbaValueRecordList valueRecordList);
  long  getGridValuesByArea(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,in octet coordinateType,in unsigned long columns,in unsigned long rows,in double x,in double y,in double xStep,in double yStep,in octet interpolationMethod,out CorbaParamValueList values);
};  


};
};
};

#endif
