#ifndef __DATA_SERVER_TYPEDEFS_IDL
#define __DATA_SERVER_TYPEDEFS_IDL

#include "Typedefs.idl"


module SmartMet
{

module C
{


struct PropertySetting
{
  C::UInt32 propertyId;
  string    propertyValue;
};

typedef sequence<PropertySetting> PropertySettingList;


struct GridData
{
  C::UInt32             serverId;
  C::ProducerId         producerId;
  C::GenerationId       generationId;
  C::FileId             fileId;
  C::FileType           fileType;
  string                fileName;
  C::MessageIndex       messageIndex;
  C::TimeString         forecastTime;
  C::ForecastType       forecastType;
  C::ForecastNumber     forecastNumber;
  string                gribParameterId;
  C::UInt32             grib1LevelId;
  C::UInt32             grib2LevelId;
  string                gribParameterName;
  string                parameterId;
  C::LevelId            levelId;
  string                parameterName;
  string                newbaseParameterId;
  string                newbaseParameterName;
  C::Level              level;
  C::GeometryId	        geometryId;
  C::Bool               reverseXDirection;
  C::Bool               reverseYDirection;
  C::UInt32             projection;
  C::UInt32             columns;
  C::UInt32             rows;  
  C::AttributeRecList   projectionAttributes;
  C::ParameterValueList valueList;
};




struct GridCoordinates
{
  C::UInt32            projection;  
  C::UInt32            columns;
  C::UInt32            rows;  
  C::Bool              reverseXDirection;
  C::Bool              reverseYDirection;
  C::AttributeRecList  projectionAttributes;
  C::CoordinateType    coordinateType;  
  C::CoordinateList    coordinateList;
};


};
};


#endif
