#ifndef __CONTENT_SERVER_TYPEDEFS_IDL
#define __CONTENT_SERVER_TYPEDEFS_IDL

#include "Typedefs.idl"


module SmartMet
{

module C
{

struct ContentInfo
{
  C::ProducerId       producerId;
  C::GenerationId     generationId;
  C::FileType         fileType;
  C::FileId           fileId;
  C::MessageIndex     messageIndex;
  C::FilePosition     filePosition;
  C::MessageSize      messageSize;
  C::TimeString       forecastTime;
  C::ForecastType     forecastType;
  C::ForecastNumber   forecastNumber;
  C::ParameterId      parameterId;
  C::ParameterName    parameterName;
  C::LevelId          levelId;
  C::Level            level;
  C::UInt32           flags;
  C::SourceId         sourceId;
  C::GeometryId       geometryId;
  C::Timestamp        modificationTime;
  C::Timestamp        deletionTime;
  C::Int32            aggregationId;
  C::Int32            aggregationPeriod;
  C::Int32            processingTypeId;
  C::Float32          processingTypeValue1;
  C::Float32          processingTypeValue2;  
};

typedef sequence<ContentInfo> ContentInfoList;



struct ProducerInfo
{
  C::ProducerId  producerId;
  string         name;
  string         title;
  string         description;
  C::UInt32      flags;
  C::SourceId    sourceId;
  C::Hash        hash;  
};

typedef sequence<ProducerInfo> ProducerInfoList;




struct FileInfo
{
  C::ProducerId    producerId;
  C::GenerationId  generationId;
  C::FileId        fileId;
  C::UInt8         protocol;
  string           server;
  C::FileType      fileType;
  string           name;
  C::FileSize      size;
  C::UInt32        flags;
  C::SourceId      sourceId;
  C::Timestamp     modificationTime;
  C::Timestamp     deletionTime;
};

typedef sequence<FileInfo> FileInfoList;




struct FileContent
{
  C::FileInfo        fileInfo;
  C::ContentInfoList contentInfoList;
};

typedef sequence<FileContent> FileContentList;




struct EventInfo
{
  C::EventId     eventId;
  C::Timestamp   eventTime;
  C::Timestamp   serverTime;
  C::UInt32      type;
  C::UInt64      id1;
  C::UInt64      id2;
  C::UInt64      id3;
  C::UInt64      flags;
  string         eventData;
};

typedef sequence<EventInfo> EventInfoList;




struct GeometryInfo
{
  C::GenerationId  generationId;
  C::GeometryId    geometryId;
  C::LevelId       levelId;
  C::ProducerId    producerId;
  C::UInt32        flags;
  C::SourceId      sourceId;
  C::Timestamp     modificationTime;
  C::Timestamp     deletionTime;
  C::Status        status;
}; 

typedef sequence<GeometryInfo> GeometryInfoList;




struct GenerationInfo
{
  C::GenerationId   generationId;
  C::GenerationType generationType;
  C::ProducerId     producerId;
  string            name;
  string            description;
  C::TimeString     analysisTime;
  C::Timestamp      deletionTime;
  C::Timestamp      modificationTime;
  C::Timestamp      contentStartTime;
  C::Timestamp      contentEndTime;
  C::Hash           contentHash;
  C::SourceId       sourceId;
  C::UInt32         flags;
  C::Status         status;
};

typedef sequence<GenerationInfo> GenerationInfoList;



struct ForecastTimeInfo
{
  C::SourceId        sourceId;
  C::GenerationId    generationId;
  C::GeometryId      geometryId;
  C::ForecastType    forecastType;
  C::ForecastNumber  forecastNumber;
  C::TimeString      forecastTime;
  C::TimeString      modificationTime;
};

typedef sequence<ForecastTimeInfo> ForecastTimeInfoList;



struct LevelInfo
{
  C::ProducerId  producerId;
  string         parameterName;
  C::LevelId     levelId;
  C::Level       level;
};

typedef sequence<LevelInfo> LevelInfoList;



};
};


#endif
