#ifndef __CONTENT_SERVER_SERVICE_INTERFACE_IDL
#define __CONTENT_SERVER_SERVICE_INTERFACE_IDL

#include "ContentServer_typedefs.idl"
#include "Typedefs.idl"


module SmartMet
{

module ContentServer
{

module Corba
{


interface ServiceInterface
{
  C::Result  clear(in C::SessionId sessionId);
  C::Result  reload(in C::SessionId sessionId);
  C::Result  getContentChangeTime(in C::SessionId sessionId,out C::Timestamp changeTime);

  C::Result  addProducerInfo(in C::SessionId sessionId,inout C::ProducerInfo producerInfo);
  C::Result  deleteProducerInfoById(in C::SessionId sessionId,in C::ProducerId producerId);
  C::Result  deleteProducerInfoByName(in C::SessionId sessionId,in string producerName);
  C::Result  deleteProducerInfoListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId);
  C::Result  getProducerInfoById(in C::SessionId sessionId,in C::ProducerId producerId,out C::ProducerInfo producerInfo);
  C::Result  getProducerInfoByName(in C::SessionId sessionId,in string producerName,out C::ProducerInfo producerInfo);
  C::Result  getProducerInfoList(in C::SessionId sessionId,out C::ProducerInfoList producerInfoList);
  C::Result  getProducerInfoListByParameter(in C::SessionId sessionId,in C::ParameterKeyType parameterKeyType,in C::ParameterKey parameterKey,out C::ProducerInfoList producerInfoList);
  C::Result  getProducerInfoListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId,out C::ProducerInfoList producerInfoList);
  C::Result  getProducerInfoCount(in C::SessionId sessionId,out C::UInt32 count);
  C::Result  getProducerNameAndGeometryList(in C::SessionId sessionId,out C::StringList list);
  C::Result  getProducerParameterList(in C::SessionId sessionId,in C::ParameterKeyType sourceParameterKeyType,in C::ParameterKeyType targetParameterKeyType,out C::StringList list);
  C::Result  getProducerParameterListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId,in C::ParameterKeyType sourceParameterKeyType,in C::ParameterKeyType targetParameterKeyType,out C::StringList list);
  C::Result  setProducerInfo(in C::SessionId sessionId,in C::ProducerInfo producerInfo);

  C::Result  addGenerationInfo(in C::SessionId sessionId,inout C::GenerationInfo generationInfo);
  C::Result  deleteGenerationInfoById(in C::SessionId sessionId,in C::GenerationId generationId);
  C::Result  deleteGenerationInfoByName(in C::SessionId sessionId,in string generationName);
  C::Result  deleteGenerationInfoListByIdList(in C::SessionId sessionId,in C::GenerationIdList generationIdList);
  C::Result  deleteGenerationInfoListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId);
  C::Result  deleteGenerationInfoListByProducerName(in C::SessionId sessionId,in string producerName);
  C::Result  deleteGenerationInfoListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId);
  C::Result  getGenerationIdGeometryIdAndForecastTimeList(in C::SessionId sessionId,out C::StringList list);
  C::Result  getGenerationInfoById(in C::SessionId sessionId,in C::GenerationId generationId,out C::GenerationInfo generationInfo);
  C::Result  getGenerationInfoByName(in C::SessionId sessionId,in string generationName,out C::GenerationInfo generationInfo);
  C::Result  getGenerationInfoList(in C::SessionId sessionId,out C::GenerationInfoList generationInfoList);
  C::Result  getGenerationInfoListByGeometryId(in C::SessionId sessionId,in C::GeometryId geometryId,out C::GenerationInfoList generationInfoList);
  C::Result  getGenerationInfoListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId,out C::GenerationInfoList generationInfoList);
  C::Result  getGenerationInfoListByProducerName(in C::SessionId sessionId,in string producerName,out C::GenerationInfoList generationInfoList);
  C::Result  getGenerationInfoListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId,out C::GenerationInfoList generationInfoList);
  C::Result  getLastGenerationInfoByProducerIdAndStatus(in C::SessionId sessionId,in C::ProducerId producerId,in C::Status generationStatus,out C::GenerationInfo generationInfo);
  C::Result  getLastGenerationInfoByProducerNameAndStatus(in C::SessionId sessionId,in string producerName,in C::Status generationStatus,out C::GenerationInfo generationInfo);
  C::Result  getGenerationInfoCount(in C::SessionId sessionId,out C::UInt32 count);
  C::Result  setGenerationInfo(in C::SessionId sessionId,in C::GenerationInfo generationInfo);
  C::Result  setGenerationInfoStatusById(in C::SessionId sessionId,in C::GenerationId generationId,in C::Status status);
  C::Result  setGenerationInfoStatusByName(in C::SessionId sessionId,in string generationName,in C::Status status);

  C::Result  addGeometryInfo(in C::SessionId sessionId,inout C::GeometryInfo geometryInfo);
  C::Result  deleteGeometryInfoById(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,in C::LevelId levelId);
  C::Result  deleteGeometryInfoListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId);
  C::Result  deleteGeometryInfoListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId);
  C::Result  deleteGeometryInfoListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId);
  C::Result  getGeometryInfoById(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,in C::LevelId levelId,out C::GeometryInfo geometryInfo);
  C::Result  getGeometryInfoList(in C::SessionId sessionId,out C::GeometryInfoList geometryInfoList);
  C::Result  getGeometryInfoListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,out C::GeometryInfoList geometryInfoList);
  C::Result  getGeometryInfoListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId,out C::GeometryInfoList geometryInfoList);
  C::Result  getGeometryInfoListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId,out C::GeometryInfoList geometryInfoList);
  C::Result  getGeometryInfoCount(in C::SessionId sessionId,out C::UInt32 count);
  C::Result  setGeometryInfo(in C::SessionId sessionId,in C::GeometryInfo geometryInfo);
  C::Result  setGeometryInfoStatusById(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,in C::LevelId levelId,in C::Status status);

  C::Result  addFileInfo(in C::SessionId sessionId,inout C::FileInfo fileInfo);
  C::Result  addFileInfoWithContentList(in C::SessionId sessionId,inout C::FileInfo fileInfo,inout C::ContentInfoList contentInfoList);
  C::Result  addFileInfoListWithContent(in C::SessionId sessionId,in C::UInt32 requestFlags,inout C::FileContentList fileContentList);
  C::Result  deleteFileInfoById(in C::SessionId sessionId,in C::FileId fileId);
  C::Result  deleteFileInfoByName(in C::SessionId sessionId,in string filename);
  C::Result  deleteFileInfoListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId);
  C::Result  deleteFileInfoListByProducerName(in C::SessionId sessionId,in string producerName);
  C::Result  deleteFileInfoListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId);
  C::Result  deleteFileInfoListByGenerationIdAndForecastTime(in C::SessionId sessionId,in C::GenerationId generationId,in C::Result  geometryId,in C::ForecastType forecastType,in C::ForecastType forecastNumber,in C::Timestamp forecastTime);
  C::Result  deleteFileInfoListByForecastTimeList(in C::SessionId sessionId,in C::ForecastTimeInfoList forecastTimeList);
  C::Result  deleteFileInfoListByGenerationName(in C::SessionId sessionId,in string generationName);
  C::Result  deleteFileInfoListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId);
  C::Result  deleteFileInfoListByFileIdList(in C::SessionId sessionId,in C::FileIdList fileIdList);
  C::Result  getFileInfoById(in C::SessionId sessionId,in C::FileId fileId,out C::FileInfo fileInfo);
  C::Result  getFileInfoByName(in C::SessionId sessionId,in string filename,out C::FileInfo fileInfo);
  C::Result  getFileInfoList(in C::SessionId sessionId,in C::FileId startFileId,in C::Int32 maxRecords,out C::FileInfoList fileInfoList);
  C::Result  getFileInfoListByFileIdList(in C::SessionId sessionId,in C::FileIdList fileIdList,out C::FileInfoList fileInfoList);
  C::Result  getFileInfoListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId,in C::FileId startFileId,in C::Int32 maxRecords,out C::FileInfoList fileInfoList);
  C::Result  getFileInfoListByProducerName(in C::SessionId sessionId,in string producerName,in C::FileId startFileId,in C::Int32 maxRecords,out C::FileInfoList fileInfoList);
  C::Result  getFileInfoListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,in C::FileId startFileId,in C::Int32 maxRecords,out C::FileInfoList fileInfoList);
  C::Result  getFileInfoListByGenerationName(in C::SessionId sessionId,in string generationName,in C::FileId startFileId,in C::Int32 maxRecords,out C::FileInfoList fileInfoList);
  C::Result  getFileInfoListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId,in C::FileId startFileId,in C::Int32 maxRecords,out C::FileInfoList fileInfoList);
  C::Result  getFileInfoCount(in C::SessionId sessionId,out C::UInt32 count);
  C::Result  getFileInfoCountByProducerId(in C::SessionId sessionId,in C::ProducerId producerId,out C::UInt32 count);
  C::Result  getFileInfoCountByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,out C::UInt32 count);
  C::Result  getFileInfoCountBySourceId(in C::SessionId sessionId,in C::SourceId sourceId,out C::UInt32 count);
  C::Result  setFileInfo(in C::SessionId sessionId,in C::FileInfo fileInfo);
  
  C::Result  addEventInfo(in C::SessionId sessionId,inout C::EventInfo eventInfo);
  C::Result  getLastEventInfo(in C::SessionId sessionId,in C::UInt32 requestingServerId,out C::EventInfo eventInfo);
  C::Result  getEventInfoList(in C::SessionId sessionId,in C::UInt32 requestingServerId,in C::EventId startEventId,in C::Int32 maxRecords,out C::EventInfoList eventInfoList);
  C::Result  getEventInfoCount(in C::SessionId sessionId,out C::UInt32 count);

  C::Result  addContentInfo(in C::SessionId sessionId,inout C::ContentInfo contentInfo);
  C::Result  addContentList(in C::SessionId sessionId,inout C::ContentInfoList contentInfoList);
  C::Result  deleteContentInfo(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex);
  C::Result  deleteContentListByFileId(in C::SessionId sessionId,in C::FileId fileId);
  C::Result  deleteContentListByFileName(in C::SessionId sessionId,in string filename);
  C::Result  deleteContentListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId);
  C::Result  deleteContentListByProducerName(in C::SessionId sessionId,in string producerName);
  C::Result  deleteContentListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId);
  C::Result  deleteContentListByGenerationName(in C::SessionId sessionId,in string generationName);
  C::Result  deleteContentListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId);

  C::Result  getContentInfo(in C::SessionId sessionId,in C::FileId fileId,in C::MessageIndex messageIndex,out C::ContentInfo contentInfo);
  C::Result  getContentList(in C::SessionId sessionId,in C::FileId startFileId,in C::MessageIndex startMessageIndex,in C::Int32 maxRecords,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByFileId(in C::SessionId sessionId,in C::FileId fileId,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByFileIdList(in C::SessionId sessionId,in C::FileIdList fileIdList,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByFileName(in C::SessionId sessionId,in string filename,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId,in C::FileId startFileId,in C::MessageIndex startMessageIndex,in C::Int32 maxRecords,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByProducerName(in C::SessionId sessionId,in string producerName,in C::FileId startFileId,in C::MessageIndex startMessageIndex,in C::Int32 maxRecords,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,in C::FileId startFileId,in C::MessageIndex startMessageIndex,in C::Int32 maxRecords,in C::UInt32 requestFlags,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByGenerationName(in C::SessionId sessionId,in string generationName,in C::FileId startFileId,in C::MessageIndex startMessageIndex,in C::Int32 maxRecords,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByGenerationIdAndTimeRange(in C::SessionId sessionId,in C::GenerationId generationId,in C::Timestamp startTime,in C::Timestamp endTime,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByGenerationNameAndTimeRange(in C::SessionId sessionId,in string generationName,in C::Timestamp startTime,in C::Timestamp endTime,out C::ContentInfoList contentInfoList);
  C::Result  getContentListBySourceId(in C::SessionId sessionId,in C::SourceId sourceId,in C::FileId startFileId,in C::MessageIndex startMessageIndex,in C::Int32 maxRecords,out C::ContentInfoList contentInfoList);

  C::Result  getContentListByParameter(in C::SessionId sessionId,in C::ParameterKeyType parameterKeyType,in C::ParameterKey parameterKey,in C::LevelId levelId,in C::Level minLevel,in C::Level maxLevel,in C::ForecastType forecastType,in C::ForecastType forecastNumber,in C::GeometryId geometryId,in C::Timestamp startTime,in C::Timestamp endTime,in C::UInt32 requestFlags,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByParameterAndGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,in C::ParameterKeyType parameterKeyType,in C::ParameterKey parameterKey,in C::LevelId levelId,in C::Level minLevel,in C::Level maxLevel,in C::ForecastType forecastType,in C::ForecastType forecastNumber,in C::GeometryId geometryId,in C::Timestamp startTime,in C::Timestamp endTime,in C::UInt32 requestFlags,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByParameterAndGenerationName(in C::SessionId sessionId,in string generationName,in C::ParameterKeyType parameterKeyType,in C::ParameterKey parameterKey,in C::LevelId levelId,in C::Level minLevel,in C::Level maxLevel,in C::ForecastType forecastType,in C::ForecastType forecastNumber,in C::GeometryId geometryId,in C::Timestamp startTime,in C::Timestamp endTime,in C::UInt32 requestFlags,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByParameterAndProducerId(in C::SessionId sessionId,in C::ProducerId producerId,in C::ParameterKeyType parameterKeyType,in C::ParameterKey parameterKey,in C::LevelId levelId,in C::Level minLevel,in C::Level maxLevel,in C::ForecastType forecastType,in C::ForecastType forecastNumber,in C::GeometryId geometryId,in C::Timestamp startTime,in C::Timestamp endTime,in C::UInt32 requestFlags,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByParameterAndProducerName(in C::SessionId sessionId,in string producerName,in C::ParameterKeyType parameterKeyType,in C::ParameterKey parameterKey,in C::LevelId levelId,in C::Level minLevel,in C::Level maxLevel,in C::ForecastType forecastType,in C::ForecastType forecastNumber,in C::GeometryId geometryId,in C::Timestamp startTime,in C::Timestamp endTime,in C::UInt32 requestFlags,out C::ContentInfoList contentInfoList);
  C::Result  getContentListByParameterGenerationIdAndForecastTime(in C::SessionId sessionId,in C::GenerationId generationId,in C::ParameterKeyType parameterKeyType,in C::ParameterKey parameterKey,in C::LevelId levelId,in C::Level level,in C::ForecastType forecastType,in C::ForecastType forecastNumber,in C::GeometryId geometryId,in C::Timestamp forecastTime,out C::ContentInfoList contentInfoList);
  
  C::Result  getContentListOfInvalidIntegrity(in C::SessionId sessionId,out C::ContentInfoList contentInfoList);
  
  C::Result  getContentGeometryIdListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,out C::GeometryIdList geometryIdList);
  C::Result  getContentLevelListByGenerationGeometryAndLevelId(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,in C::LevelId levelId,out C::LevelList contentLevelList);
  C::Result  getContentLevelListByParameterGenerationGeometryAndLevelId(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,in C::ParameterKey parameterKey,in C::LevelId levelId,out C::LevelList contentLevelList);
  C::Result  getContentParamListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,out C::ContentInfoList contentParamList);
  C::Result  getContentParamKeyListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,in C::ParameterKeyType parameterKeyType,out C::StringList paramKeyList);
  C::Result  getContentParamKeyListByGenerationAndGeometryId(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,in C::ParameterKeyType parameterKeyType,out C::StringList paramKeyList);
  C::Result  getContentParamKeyListByGenerationGeometryAndLevelId(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,in C::LevelId levelId,in C::ParameterKeyType parameterKeyType,out C::StringList paramKeyList);
  C::Result  getContentTimeListByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,out C::TimeStringList contentTimeList);
  C::Result  getContentTimeListByGenerationAndGeometryId(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,out C::TimeStringList contentTimeList);
  C::Result  getContentTimeListByGenerationGeometryAndLevelId(in C::SessionId sessionId,in C::GenerationId generationId,in C::GeometryId geometryId,in C::LevelId levelId,out C::TimeStringList contentTimeList);
  C::Result  getContentTimeListByProducerId(in C::SessionId sessionId,in C::ProducerId producerId,out C::TimeStringList contentTimeList);
  C::Result  getContentTimeRangeByProducerAndGenerationId(in C::SessionId sessionId,in C::ProducerId producerId,in C::GenerationId generationId,out C::Timestamp startTime,out C::Timestamp endTime);
  C::Result  getContentTimeRangeByGenerationId(in C::SessionId sessionId,in C::GenerationId generationId,out C::Timestamp startTime,out C::Timestamp endTime);

  C::Result  getContentCount(in C::SessionId sessionId,out C::UInt32 count);
  C::Result  setContentInfo(in C::SessionId sessionId,in C::ContentInfo contentInfo);

  C::Result  getHashByProducerId(in C::SessionId sessionId,in C::ProducerId producerId,out C::Hash hash);

  C::Result  getLevelInfoList(in C::SessionId sessionId,out C::LevelInfoList levelInfoList);
};  


};
};
};

#endif
