#ifndef __CONTENT_SERVER_SERVICE_INTERFACE_IDL
#define __CONTENT_SERVER_SERVICE_INTERFACE_IDL

#include "ContentServer_typedefs.idl"


module SmartMet
{

module ContentServer
{

module Corba
{


interface ServiceInterface
{
  long  clear(in long long sessionId);
  long  reload(in long long sessionId);

  long  addProducerInfo(in long long sessionId,inout CorbaProducerInfo producerInfo);
  long  deleteProducerInfoById(in long long sessionId,in unsigned long producerId);
  long  deleteProducerInfoByName(in long long sessionId,in string producerName);
  long  deleteProducerInfoListBySourceId(in long long sessionId,in unsigned long sourceId);
  long  getProducerInfoById(in long long sessionId,in unsigned long producerId,out CorbaProducerInfo producerInfo);
  long  getProducerInfoByName(in long long sessionId,in string producerName,out CorbaProducerInfo producerInfo);
  long  getProducerInfoList(in long long sessionId,out CorbaProducerInfoList producerInfoList);
  long  getProducerInfoListByParameter(in long long sessionId,in octet parameterKeyType,in string parameterKey,out CorbaProducerInfoList producerInfoList);
  long  getProducerInfoListBySourceId(in long long sessionId,in unsigned long sourceId,out CorbaProducerInfoList producerInfoList);
  long  getProducerInfoCount(in long long sessionId,out unsigned long count);
  long  getProducerNameAndGeometryList(in long long sessionId,out CorbaStringList list);
  long  getProducerParameterList(in long long sessionId,in octet sourceParameterKeyType,in octet targetParameterKeyType,out CorbaStringList list);
  long  getProducerParameterListByProducerId(in long long sessionId,in unsigned long producerId,in octet sourceParameterKeyType,in octet targetParameterKeyType,out CorbaStringList list);

  long  addGenerationInfo(in long long sessionId,inout CorbaGenerationInfo generationInfo);
  long  deleteGenerationInfoById(in long long sessionId,in unsigned long generationId);
  long  deleteGenerationInfoByName(in long long sessionId,in string generationName);
  long  deleteGenerationInfoListByIdList(in long long sessionId,in CorbaULongList generationIdList);
  long  deleteGenerationInfoListByProducerId(in long long sessionId,in unsigned long producerId);
  long  deleteGenerationInfoListByProducerName(in long long sessionId,in string producerName);
  long  deleteGenerationInfoListBySourceId(in long long sessionId,in unsigned long sourceId);
  long  getGenerationIdGeometryIdAndForecastTimeList(in long long sessionId,out CorbaStringList list);
  long  getGenerationInfoById(in long long sessionId,in unsigned long generationId,out CorbaGenerationInfo generationInfo);
  long  getGenerationInfoByName(in long long sessionId,in string generationName,out CorbaGenerationInfo generationInfo);
  long  getGenerationInfoList(in long long sessionId,out CorbaGenerationInfoList generationInfoList);
  long  getGenerationInfoListByGeometryId(in long long sessionId,in long geometryId,out CorbaGenerationInfoList generationInfoList);
  long  getGenerationInfoListByProducerId(in long long sessionId,in unsigned long producerId,out CorbaGenerationInfoList generationInfoList);
  long  getGenerationInfoListByProducerName(in long long sessionId,in string producerName,out CorbaGenerationInfoList generationInfoList);
  long  getGenerationInfoListBySourceId(in long long sessionId,in unsigned long sourceId,out CorbaGenerationInfoList generationInfoList);
  long  getLastGenerationInfoByProducerIdAndStatus(in long long sessionId,in unsigned long producerId,in octet generationStatus,out CorbaGenerationInfo generationInfo);
  long  getLastGenerationInfoByProducerNameAndStatus(in long long sessionId,in string producerName,in octet generationStatus,out CorbaGenerationInfo generationInfo);
  long  getGenerationInfoCount(in long long sessionId,out unsigned long count);
  long  setGenerationInfoStatusById(in long long sessionId,in unsigned long generationId,in octet status);
  long  setGenerationInfoStatusByName(in long long sessionId,in string generationName,in octet status);

  long  addFileInfo(in long long sessionId,inout CorbaFileInfo fileInfo);
  long  addFileInfoWithContentList(in long long sessionId,inout CorbaFileInfo fileInfo,inout CorbaContentInfoList contentInfoList);
  long  addFileInfoListWithContent(in long long sessionId,in unsigned long requestFlags,inout CorbaFileContentList fileContentList);
  long  deleteFileInfoById(in long long sessionId,in unsigned long fileId);
  long  deleteFileInfoByName(in long long sessionId,in string filename);
  long  deleteFileInfoListByGroupFlags(in long long sessionId,in unsigned long groupFlags);
  long  deleteFileInfoListByProducerId(in long long sessionId,in unsigned long producerId);
  long  deleteFileInfoListByProducerName(in long long sessionId,in string producerName);
  long  deleteFileInfoListByGenerationId(in long long sessionId,in unsigned long generationId);
  long  deleteFileInfoListByGenerationIdAndForecastTime(in long long sessionId,in unsigned long generationId,in long  geometryId,in short forecastType,in short forecastNumber,in string forecastTime);
  long  deleteFileInfoListByForecastTimeList(in long long sessionId,in CorbaForecastTimeList forecastTimeList);
  long  deleteFileInfoListByGenerationName(in long long sessionId,in string generationName);
  long  deleteFileInfoListBySourceId(in long long sessionId,in unsigned long sourceId);
  long  deleteFileInfoListByFileIdList(in long long sessionId,in CorbaULongList fileIdList);
  long  getFileInfoById(in long long sessionId,in unsigned long fileId,out CorbaFileInfo fileInfo);
  long  getFileInfoByName(in long long sessionId,in string filename,out CorbaFileInfo fileInfo);
  long  getFileInfoList(in long long sessionId,in unsigned long startFileId,in unsigned long maxRecords,out CorbaFileInfoList fileInfoList);
  long  getFileInfoListByFileIdList(in long long sessionId,in CorbaULongList fileIdList,out CorbaFileInfoList fileInfoList);
  long  getFileInfoListByProducerId(in long long sessionId,in unsigned long producerId,in unsigned long startFileId,in unsigned long maxRecords,out CorbaFileInfoList fileInfoList);
  long  getFileInfoListByProducerName(in long long sessionId,in string producerName,in unsigned long startFileId,in unsigned long maxRecords,out CorbaFileInfoList fileInfoList);
  long  getFileInfoListByGenerationId(in long long sessionId,in unsigned long generationId,in unsigned long startFileId,in unsigned long maxRecords,out CorbaFileInfoList fileInfoList);
  long  getFileInfoListByGenerationName(in long long sessionId,in string generationName,in unsigned long startFileId,in unsigned long maxRecords,out CorbaFileInfoList fileInfoList);
  long  getFileInfoListByGroupFlags(in long long sessionId,in unsigned long groupFlags,in unsigned long startFileId,in unsigned long maxRecords,out CorbaFileInfoList fileInfoList);
  long  getFileInfoListBySourceId(in long long sessionId,in unsigned long sourceId,in unsigned long startFileId,in unsigned long maxRecords,out CorbaFileInfoList fileInfoList);
  long  getFileInfoCount(in long long sessionId,out unsigned long count);
  long  getFileInfoCountByProducerId(in long long sessionId,in unsigned long producerId,out unsigned long count);
  long  getFileInfoCountByGenerationId(in long long sessionId,in unsigned long generationId,out unsigned long count);
  long  getFileInfoCountBySourceId(in long long sessionId,in unsigned long sourceId,out unsigned long count);
  
  long  addEventInfo(in long long sessionId,inout CorbaEventInfo eventInfo);
  long  getLastEventInfo(in long long sessionId,in unsigned long requestingServerId,out CorbaEventInfo eventInfo);
  long  getEventInfoList(in long long sessionId,in unsigned long requestingServerId,in unsigned long long startEventId,in unsigned long maxRecords,out CorbaEventInfoList eventInfoList);
  long  getEventInfoCount(in long long sessionId,out unsigned long count);

  long  addContentInfo(in long long sessionId,inout CorbaContentInfo contentInfo);
  long  addContentList(in long long sessionId,inout CorbaContentInfoList contentInfoList);
  long  deleteContentInfo(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex);
  long  deleteContentListByFileId(in long long sessionId,in unsigned long fileId);
  long  deleteContentListByFileName(in long long sessionId,in string filename);
  long  deleteContentListByGroupFlags(in long long sessionId,in unsigned long groupFlags);
  long  deleteContentListByProducerId(in long long sessionId,in unsigned long producerId);
  long  deleteContentListByProducerName(in long long sessionId,in string producerName);
  long  deleteContentListByGenerationId(in long long sessionId,in unsigned long generationId);
  long  deleteContentListByGenerationName(in long long sessionId,in string generationName);
  long  deleteContentListBySourceId(in long long sessionId,in unsigned long sourceId);

  long  getContentInfo(in long long sessionId,in unsigned long fileId,in unsigned long messageIndex,out CorbaContentInfo contentInfo);
  long  getContentList(in long long sessionId,in unsigned long startFileId,in unsigned long startMessageIndex,in unsigned long maxRecords,out CorbaContentInfoList contentInfoList);
  long  getContentListByFileId(in long long sessionId,in unsigned long fileId,out CorbaContentInfoList contentInfoList);
  long  getContentListByFileIdList(in long long sessionId,in CorbaULongList fileIdList,out CorbaContentInfoList contentInfoList);
  long  getContentListByFileName(in long long sessionId,in string filename,out CorbaContentInfoList contentInfoList);
  long  getContentListByGroupFlags(in long long sessionId,in unsigned long groupFlags,in unsigned long startFileId,in unsigned long startMessageIndex,in unsigned long maxRecords,out CorbaContentInfoList contentInfoList);
  long  getContentListByProducerId(in long long sessionId,in unsigned long producerId,in unsigned long startFileId,in unsigned long startMessageIndex,in unsigned long maxRecords,out CorbaContentInfoList contentInfoList);
  long  getContentListByProducerName(in long long sessionId,in string producerName,in unsigned long startFileId,in unsigned long startMessageIndex,in unsigned long maxRecords,out CorbaContentInfoList contentInfoList);
  long  getContentListByGenerationId(in long long sessionId,in unsigned long generationId,in unsigned long startFileId,in unsigned long startMessageIndex,in unsigned long maxRecords,in unsigned long requestFlags,out CorbaContentInfoList contentInfoList);
  long  getContentListByGenerationName(in long long sessionId,in string generationName,in unsigned long startFileId,in unsigned long startMessageIndex,in unsigned long maxRecords,out CorbaContentInfoList contentInfoList);
  long  getContentListByGenerationIdAndTimeRange(in long long sessionId,in unsigned long generationId,in string startTime,in string endTime,out CorbaContentInfoList contentInfoList);
  long  getContentListByGenerationNameAndTimeRange(in long long sessionId,in string generationName,in string startTime,in string endTime,out CorbaContentInfoList contentInfoList);
  long  getContentListBySourceId(in long long sessionId,in unsigned long sourceId,in unsigned long startFileId,in unsigned long startMessageIndex,in unsigned long maxRecords,out CorbaContentInfoList contentInfoList);

  long  getContentListByParameter(in long long sessionId,in octet parameterKeyType,in string parameterKey,in octet parameterLevelIdType,in unsigned long parameterLevelId,in long minLevel,in long maxLevel,in short forecastType,in short forecastNumber,in long geometryId,in string startTime,in string endTime,in unsigned long requestFlags,out CorbaContentInfoList contentInfoList);
  long  getContentListByParameterAndGenerationId(in long long sessionId,in unsigned long generationId,in octet parameterKeyType,in string parameterKey,in octet parameterLevelIdType,in unsigned long parameterLevelId,in long minLevel,in long maxLevel,in short forecastType,in short forecastNumber,in long geometryId,in string startTime,in string endTime,in unsigned long requestFlags,out CorbaContentInfoList contentInfoList);
  long  getContentListByParameterAndGenerationName(in long long sessionId,in string generationName,in octet parameterKeyType,in string parameterKey,in octet parameterLevelIdType,in unsigned long parameterLevelId,in long minLevel,in long maxLevel,in short forecastType,in short forecastNumber,in long geometryId,in string startTime,in string endTime,in unsigned long requestFlags,out CorbaContentInfoList contentInfoList);
  long  getContentListByParameterAndProducerId(in long long sessionId,in unsigned long producerId,in octet parameterKeyType,in string parameterKey,in octet parameterLevelIdType,in unsigned long parameterLevelId,in long minLevel,in long maxLevel,in short forecastType,in short forecastNumber,in long geometryId,in string startTime,in string endTime,in unsigned long requestFlags,out CorbaContentInfoList contentInfoList);
  long  getContentListByParameterAndProducerName(in long long sessionId,in string producerName,in octet parameterKeyType,in string parameterKey,in octet parameterLevelIdType,in unsigned long parameterLevelId,in long minLevel,in long maxLevel,in short forecastType,in short forecastNumber,in long geometryId,in string startTime,in string endTime,in unsigned long requestFlags,out CorbaContentInfoList contentInfoList);
  long  getContentListByParameterGenerationIdAndForecastTime(in long long sessionId,in unsigned long generationId,in octet parameterKeyType,in string parameterKey,in octet parameterLevelIdType,in unsigned long parameterLevelId,in long level,in short forecastType,in short forecastNumber,in long geometryId,in string forecastTime,out CorbaContentInfoList contentInfoList);
  
  long  getContentListOfInvalidIntegrity(in long long sessionId,out CorbaContentInfoList contentInfoList);
  
  long  getContentGeometryIdListByGenerationId(in long long sessionId,in unsigned long generationId,out CorbaLongList geometryIdList);
  long  getContentParamListByGenerationId(in long long sessionId,in unsigned long generationId,out CorbaContentInfoList contentParamList);
  long  getContentParamKeyListByGenerationId(in long long sessionId,in unsigned long generationId,in octet parameterKeyType,out CorbaStringList paramKeyList);
  long  getContentTimeListByGenerationId(in long long sessionId,in unsigned long generationId,out CorbaStringList contentTimeList);
  long  getContentTimeListByGenerationAndGeometryId(in long long sessionId,in unsigned long generationId,in long geometryId,out CorbaStringList contentTimeList);
  long  getContentTimeListByProducerId(in long long sessionId,in unsigned long producerId,out CorbaStringList contentTimeList);

  long  getContentCount(in long long sessionId,out unsigned long count);
  long  getHashByProducerId(in long long sessionId,in unsigned long producerId,out unsigned long long hash);

  long  getLevelInfoList(in long long sessionId,out CorbaLevelInfoList levelInfoList);

  long  deleteVirtualContent(in long long sessionId);
  long  updateVirtualContent(in long long sessionId);
};  


};
};
};

#endif
