#ifndef __CONTENT_SERVER_TYPEDEFS_IDL
#define __CONTENT_SERVER_TYPEDEFS_IDL


module SmartMet
{

module ContentServer
{

module Corba
{


typedef sequence<string> CorbaStringList;
typedef sequence<unsigned long> CorbaULongList;
typedef sequence<long> CorbaLongList;


struct CorbaContentInfo
{
  unsigned long      producerId;
  unsigned long      generationId;
  octet              fileType;
  unsigned long      fileId;
  unsigned long      messageIndex;
  unsigned long long filePosition;
  unsigned long      messageSize;
  string             forecastTime;
  short              forecastType;
  short              forecastNumber;
  unsigned long      fmiParameterId;
  string             fmiParameterName;
  short              fmiParameterLevelId;
  long               parameterLevel;
  unsigned long      flags;
  unsigned long      sourceId;
  long               geometryId;
  long long          modificationTime;
  long long          deletionTime;
};

typedef sequence<CorbaContentInfo> CorbaContentInfoList;



struct CorbaProducerInfo
{
  unsigned long      producerId;
  string             name;
  string             title;
  string             description;
  unsigned long      flags;
  unsigned long      sourceId;
  unsigned long long hash;  
};

typedef sequence<CorbaProducerInfo> CorbaProducerInfoList;




struct CorbaFileInfo
{
  unsigned long      producerId;
  unsigned long      generationId;
  unsigned long      fileId;
  octet              fileType;
  string             name;
  unsigned long      flags;
  unsigned long      sourceId;
  long long          modificationTime;
  long long          deletionTime;
};

typedef sequence<CorbaFileInfo> CorbaFileInfoList;




struct CorbaFileContent
{
  CorbaFileInfo        fileInfo;
  CorbaContentInfoList contentInfoList;
};

typedef sequence<CorbaFileContent> CorbaFileContentList;




struct CorbaEventInfo
{
  unsigned long long eventId;
  unsigned long      eventTime;
  unsigned long      serverTime;
  unsigned long      type;
  unsigned long      id1;
  unsigned long      id2;
  unsigned long      id3;
  unsigned long long flags;
  string             note;
};

typedef sequence<CorbaEventInfo> CorbaEventInfoList;




struct CorbaGenerationInfo
{
  unsigned long      generationId;
  unsigned long      generationType;
  unsigned long      producerId;
  string             name;
  string             description;
  string             analysisTime;
  octet              status;
  unsigned long      flags;
  unsigned long      sourceId;
  long long          deletionTime;
  long long          modificationTime;
};

typedef sequence<CorbaGenerationInfo> CorbaGenerationInfoList;



struct CorbaForecastTime
{
  unsigned long  sourceId;
  unsigned long  generationId;
  unsigned long  geometryId;
  short          forecastType;
  short          forecastNumber;
  string      	 forecastTime;
  string      	 modificationTime;
};

typedef sequence<CorbaForecastTime> CorbaForecastTimeList;



struct CorbaLevelInfo
{
  unsigned long producerId;
  string        fmiParameterName;
  short         fmiParameterLevelId;
  //octet         grib1ParameterLevelId;
  //octet         grib2ParameterLevelId;
  long          parameterLevel;
};

typedef sequence<CorbaLevelInfo> CorbaLevelInfoList;


};
};
};


#endif
