#pragma once

#include "../../definition/ServiceInterface.h"
#include "../stubs/DataServer_serviceInterface_SK.h"


// This file contains the actual implementation of the CORBA server interface. Every time
// you modify the IDL file, a new skeleton will be generated into the "stubs" directory.
// Copy the new service interface (or its changes) from the "*_i.cc" file into this file and
// write the actual implementation. The point is that we do not use "*_i.cc" file in our build,
// because it is overwritten every time when the IDL file is changes.


namespace SmartMet
{
namespace DataServer
{
namespace Corba
{

class ServerInterface : public POA_SmartMet::DataServer::Corba::ServiceInterface
{
  public:
                  ServerInterface();
    virtual       ~ServerInterface();

    void          init(DataServer::ServiceInterface *service);

    SmartMet::C::Result getGridAttributeList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::AttributeRecList_out attributeList);
    SmartMet::C::Result getGridProperties(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::PropertySettingList_out propertyList);
    SmartMet::C::Result getGridCoordinates(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, SmartMet::C::GridCoordinates_out coordinates);
    SmartMet::C::Result getGridLatlonCoordinatesByGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::GridCoordinates_out coordinates);
    SmartMet::C::Result getGridData(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::GridData_out data);
    SmartMet::C::Result getGridFileCount(SmartMet::C::SessionId sessionId, SmartMet::C::UInt32& count);
    SmartMet::C::Result getGridMessageBytes(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::ByteData_out messageBytes, SmartMet::C::UInt32List_out messageSections);
    SmartMet::C::Result getPropertyValuesByCoordinates(SmartMet::C::SessionId sessionId, const char* propertyName, const SmartMet::C::CoordinateList& latlonCoordinates, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueByPoint(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 x, SmartMet::C::Float64 y, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValue& value);
    SmartMet::C::Result getGridValueByLevelAndPoint(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::Int32 level1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Int32 level2, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 x, SmartMet::C::Float64 y, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValue& value);
    SmartMet::C::Result getGridValueByTimeAndPoint(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 x, SmartMet::C::Float64 y, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValue& value);
    SmartMet::C::Result getGridValueByTimeLevelAndPoint(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::Int32 level1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Int32 level2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::Int32 level3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Int32 level4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 x, SmartMet::C::Float64 y, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValue& value);
    SmartMet::C::Result getGridValueListByCircle(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 origoX, SmartMet::C::Float64 origoY, SmartMet::C::Float64 radius, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByPointList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& pointList, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByPolygon(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& polygonPoints, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByPolygonPath(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::PolygonPath& polygonPath, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByLevelAndCircle(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 origoX, SmartMet::C::Float64 origoY, SmartMet::C::Float64 radius, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByLevelAndPointList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& pointList, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByLevelAndPolygon(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& polygonPoints, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByLevelAndPolygonPath(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::PolygonPath& polygonPath, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByRectangle(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 x1, SmartMet::C::Float64 y1, SmartMet::C::Float64 x2, SmartMet::C::Float64 y2, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByTimeAndCircle(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 origoX, SmartMet::C::Float64 origoY, SmartMet::C::Float64 radius, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByTimeAndPointList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& pointList, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByTimeAndPolygon(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& polygonPoints, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByTimeAndPolygonPath(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::PolygonPath& polygonPath, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByTimeLevelAndCircle(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 origoX, SmartMet::C::Float64 origoY, SmartMet::C::Float64 radius, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByTimeLevelAndPointList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& pointList, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByTimeLevelAndPolygon(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& polygonPoints, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueListByTimeLevelAndPolygonPath(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::PolygonPath& polygonPath, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::GridValueList_out valueList);
    SmartMet::C::Result getGridValueVector(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByCoordinateList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& coordinates, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByRectangle(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, SmartMet::C::UInt32 columns, SmartMet::C::UInt32 rows, SmartMet::C::Float64 x, SmartMet::C::Float64 y, SmartMet::C::Float64 xStep, SmartMet::C::Float64 yStep, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByLevel(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByLevelAndCoordinateList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& coordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByLevelAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByTime(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByTimeAndCoordinateList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& coordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByTimeAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByTimeAndLevel(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::Int16 areaInterpolationMethod, SmartMet::C::Int16 timeInterpolationMethod, SmartMet::C::Int16 levelInterpolationMethod, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByTimeLevelAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridValueVectorByTimeLevelAndCoordinateList(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::CoordinateType coordinateType, const SmartMet::C::CoordinateList& coordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ParameterValueList_out values);
    SmartMet::C::Result getGridIsobands(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByLevel(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByLevelAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByLevelAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByTime(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByTimeAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByTimeAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByTimeAndLevel(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByTimeLevelAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsobandsByTimeLevelAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourLowValues, const SmartMet::C::ParameterValueList& contourHighValues, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolines(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByLevel(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByLevelAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByLevelAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByTime(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByTimeAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByTimeAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByTimeAndLevel(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByTimeLevelAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridIsolinesByTimeLevelAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, const SmartMet::C::ParameterValueList& contourValues, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out contours);
    SmartMet::C::Result getGridStreamlines(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByLevel(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByLevelAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByLevelAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Float64 newLevel, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByTime(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByTimeAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByTimeAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::Timestamp newTime, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByTimeAndLevel(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByTimeLevelAndGeometry(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridStreamlinesByTimeLevelAndGrid(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId1, SmartMet::C::MessageIndex messageIndex1, SmartMet::C::FileId fileId2, SmartMet::C::MessageIndex messageIndex2, SmartMet::C::FileId fileId3, SmartMet::C::MessageIndex messageIndex3, SmartMet::C::FileId fileId4, SmartMet::C::MessageIndex messageIndex4, SmartMet::C::Timestamp newTime, SmartMet::C::Float64 newLevel, SmartMet::C::UInt32 gridWidth, SmartMet::C::UInt32 gridHeight, const SmartMet::C::CoordinateList& gridLatLonCoordinates, SmartMet::C::AttributeRecList& attributeList, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ByteDataSequence_out streamlines);
    SmartMet::C::Result getGridValueVectorByPoint(SmartMet::C::SessionId sessionId, SmartMet::C::FileId fileId, SmartMet::C::MessageIndex messageIndex, SmartMet::C::CoordinateType coordinateType, SmartMet::C::Float64 x, SmartMet::C::Float64 y, SmartMet::C::UInt32 vectorType, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::Float64List_out valueVector);
    SmartMet::C::Result getMultipleGridValues(SmartMet::C::SessionId sessionId, SmartMet::C::UInt32 modificationOperation, const SmartMet::C::Float64List& modificationParameters, SmartMet::C::ValueRecordList& valueRecordList);

  protected:

    DataServer::ServiceInterface *mService;
};

}
}
}

