#ifndef __QUERY_SERVER_TYPEDEFS_IDL
#define __QUERY_SERVER_TYPEDEFS_IDL

#include "Typedefs.idl"


module SmartMet
{

module C
{


struct FunctionParam
{
  C::UInt32 id;
  string    param;
};

typedef sequence<FunctionParam> FunctionParamList;





struct ParameterValues
{
  // string               forecastTime;
  C::Timestamp            forecastTimeUTC;
  C::ProducerId           producerId;
  C::GenerationId         generationId;
  C::UInt64               generationFlags;
  C::GeometryId           geometryId;
  C::FileId               fileId[4];
  C::MessageIndex         messageIndex[4];
  C::Timestamp            modificationTime;
  C::TimeString           analysisTime;
  C::ParameterKeyType     parameterKeyType;
  C::ParameterKey         parameterKey;
  C::LevelId              levelId;
  C::Level                level;
  C::ForecastType         forecastType;
  C::ForecastNumber       forecastNumber;
  C::UInt32               flags;
  C::GridValueList        valueList;
  C::ParameterValueList   valueVector;
  C::ByteDataSequence     valueData;
};

typedef sequence<ParameterValues> ParameterValuesList;



struct QueryParameter
{
  C::UInt32                id;
  C::UInt32                alternativeParamId;
  C::UInt8                 type;
  C::UInt8                 locationType;
  string                   param;
  string                   origParam;
  string                   symbolicName;
  string                   producerName;
  C::GeometryId            geometryId;
  C::ParameterKeyType      parameterKeyType;
  C::ParameterKey          parameterKey;
  C::LevelId               levelId;
  C::Level                 level;
  C::ForecastType          forecastType;
  C::ForecastNumber        forecastNumber;
  C::Int16                 areaInterpolationMethod;
  C::Int16                 timeInterpolationMethod;
  C::Int16                 levelInterpolationMethod;
  C::ParameterValueList    contourLowValues;
  C::ParameterValueList    contourHighValues;
  C::UInt32List            contourColors;
  C::ProducerId            producerId;
  C::UInt64                generationFlags;
  C::Int16                 precision;
  C::UInt32                timestepsBefore;
  C::UInt32                timestepsAfter;
  C::UInt32                timestepSizeInMinutes;
  C::UInt32      	       flags;
  string                   function;
  FunctionParamList        functionParams;
  ParameterValuesList      valueList;
  C::LevelList             levels;
  C::CoordinateList        coordinates;
  AttributeRecList         attributeList;
};

typedef sequence<QueryParameter> QueryParameterList;




struct Query
{
  C::UInt8                 searchType;
  C::StringList            producerNameList;
  string                   timezone;
  C::Timestamp             startTime;
  C::Timestamp             endTime;
  C::UInt32                timesteps;
  C::UInt32                timestepSizeInMinutes;
  C::TimeString            analysisTime;
  C::GeometryIdList        geometryIdList;
  C::TimestampList         forecastTimeList;
  C::AttributeRecList      attributeList;
  C::UInt8                 coordinateType;
  C::AreaCoordinates       areaCoordinates;
  C::Float64               radius;
  C::QueryParameterList    queryParameterList;
  string                   language;
  C::UInt64                generationFlags;
  C::UInt32                flags;
  C::UInt32                maxParameterValues;
};

typedef sequence<Query> QueryList;


};
};



#endif
