#ifndef __QUERY_SERVER_TYPEDEFS_IDL
#define __QUERY_SERVER_TYPEDEFS_IDL


module SmartMet
{

module QueryServer
{

module Corba
{

typedef sequence<octet> CorbaByteData;
typedef sequence<CorbaByteData> CorbaByteDataSequence;

typedef float CorbaParamValue;
typedef sequence<CorbaParamValue> CorbaParamValueList;


typedef sequence<string> CorbaStringList;

typedef sequence<long> CorbaLongList;
typedef sequence<unsigned long long> CorbaULongLongList;
typedef sequence<unsigned long> CorbaULongList;


struct CorbaAttribute
{
  string name;
  string value;
};

typedef sequence<CorbaAttribute> CorbaAttributeList;



struct CorbaCoordinate
{
  double x;
  double y;
};

typedef sequence<CorbaCoordinate> CorbaCoordinateList;
typedef sequence<CorbaCoordinateList> CorbaAreaCoordinates;




struct CorbaGridPointValue
{
  unsigned long fileId;
  unsigned long messageIndex;
  long long     time;
  double        value;
  double        x;
  double        y;
  long          level;
};

typedef sequence<CorbaGridPointValue> CorbaGridPointValueList;




struct CorbaGridValue
{
  double x;
  double y;
  double value;
  string valueString;
};

typedef sequence<CorbaGridValue> CorbaGridValueList;




struct CorbaFunctionParam
{
  unsigned long id;
  string        param;
};

typedef sequence<CorbaFunctionParam> CorbaFunctionParamList;





struct CorbaParameterValues
{
  // string               forecastTime;
  unsigned long long      forecastTimeUTC;
  unsigned long           producerId;
  unsigned long           generationId;
  unsigned long long      generationFlags;
  unsigned long           geometryId;
  unsigned long           fileId[4];
  unsigned long           messageIndex[4];
  unsigned long long      modificationTime;
  string                  analysisTime;
  octet                   parameterKeyType;
  string                  parameterKey;
  octet                   parameterLevelId;
  long                    parameterLevel;
  short                   forecastType;
  short                   forecastNumber;
  unsigned long           flags;
  CorbaGridValueList      valueList;
  CorbaParamValueList     valueVector;
  CorbaByteDataSequence   valueData;
};

typedef sequence<CorbaParameterValues> CorbaParameterValuesList;



struct CorbaQueryParameter
{
  unsigned long            id;
  unsigned long            alternativeParamId;
  octet                    type;
  octet                    locationType;
  string                   param;
  string                   origParam;
  string                   symbolicName;
  string                   producerName;
  long                     geometryId;
  octet                    parameterKeyType;
  string                   parameterKey;
  octet                    parameterLevelId;
  long                     parameterLevel;
  short                    forecastType;
  short                    forecastNumber;
  short                    areaInterpolationMethod;
  short                    timeInterpolationMethod;
  short                    levelInterpolationMethod;
  CorbaParamValueList      contourLowValues;
  CorbaParamValueList      contourHighValues;
  CorbaULongList           contourColors;
  unsigned long            producerId;
  unsigned long long       generationFlags;
  short                    precision;
  unsigned long            timestepsBefore;
  unsigned long            timestepsAfter;
  unsigned long            timestepSizeInMinutes;
  unsigned long      	     flags;
  string                   function;
  CorbaFunctionParamList   functionParams;
  CorbaParameterValuesList valueList;
  CorbaCoordinateList      coordinates;
  CorbaAttributeList       attributeList;
};

typedef sequence<CorbaQueryParameter> CorbaQueryParameterList;




struct CorbaQuery
{
  octet                    searchType;
  CorbaStringList          producerNameList;
  string                   timezone;
  unsigned long long       startTime;
  unsigned long long       endTime;
  unsigned long            timesteps;
  unsigned long            timestepSizeInMinutes;
  string                   analysisTime;
  CorbaLongList            geometryIdList;
  CorbaULongLongList       forecastTimeList;
  CorbaAttributeList       attributeList;
  octet                    coordinateType;
  CorbaAreaCoordinates     areaCoordinates;
  double                   radius;
  CorbaQueryParameterList  queryParameterList;
  string                   language;
  unsigned long long       generationFlags;
  unsigned long            flags;
  unsigned long            maxParameterValues;
};

typedef sequence<CorbaQuery> CorbaQueryList;


};
};
};


#endif
