#ifndef __QUERY_SERVER_SERVICE_INTERFACE_IDL
#define __QUERY_SERVER_SERVICE_INTERFACE_IDL

#include "QueryServer_typedefs.idl"
#include "ContentServer_typedefs.idl"


module SmartMet
{

module QueryServer
{

module Corba
{


interface ServiceInterface
{
  C::Result  executeQuery(in C::SessionId sessionId,inout C::Query query);
  C::Result  getProducerList(in C::SessionId sessionId,out C::StringList producerList);
  C::Result  getValuesByGridPoint(in C::SessionId sessionId,in C::ContentInfoList contentInfoList,in C::UInt8 coordinateType,in C::Float64 x,in C::Float64 y,in C::Int16 interpolationMethod,out C::GridPointValueList valueList);
};  


};
};
};

#endif
